---
- name: check cluster
  azure.azcollection.azure_rm_openshiftmanagedcluster_info:
    resource_group: "{{ azr_resource_group }}"
    name: "{{ azr_aro_cluster }}"
  register: _aro_check
  failed_when: False
  changed_when: False

- fail:
    msg: |
      Cluster {{ azr_aro_cluster }} failed to provision.
      Cluster Status:
      {{ _aro_check }}
  when: (_aro_check.clusters != {}) and
        (_aro_check.clusters.properties.provisioningState == "Failed")

- debug:
    msg: |
      A cluster with the name {{ azr_aro_cluster }} already exists.
      Skipping RBAC and Cluster Creation.
  when: _aro_check.clusters != {}

- when:
    - _aro_check.clusters == {}
  block:
    - name: what cluster am i creating?
      debug:
        msg: |
          ***************************************
          Preparing to create {{ azr_aro_cluster }}.
          This task may take up to an hour.
          ***************************************
        verbosity: 0

    - include_tasks: rbac.yml

    - name: Create openshift cluster
      azure_rm_openshiftmanagedcluster:
        resource_group: "{{ azr_resource_group }}"
        name: "{{ azr_aro_cluster }}"
        location: "{{ azr_location }}"
        ingress_profiles:
          - visibility: "{{ azr_aro_public_ingress | ternary('Public', 'Private') }}"
        api_server_profile:
          visibility: "{{ azr_aro_public_api | ternary('Public', 'Private') }}"
        service_principal_profile:
          client_id: "{{ azr_service_principal_application_id }}"
          client_secret: "{{ azr_service_principal_application_secret }}"
        network_profile:
          pod_cidr: "10.128.0.0/14"
          service_cidr: "172.30.0.0/16"
        worker_profiles:
          - vm_size : "Standard_D4s_v3"
            subnet_id : "{{ _machine_subnet.state.id }}"
            disk_size : 128
            count : 3
            name: worker
        master_profile:
          vm_size : "Standard_D8s_v3"
          subnet_id: "{{ _control_subnet.state.id }}"
